Repository dnd-side-project/dnd-6th-5-backend, pull requests merged in 2022-02, with the labels that each got.

#9 environment: create User entity
  .eslintrc.json
  @types/types.d.ts
  package.json
  proxy/nginx.conf
  srcs/entity/Comment.ts
  srcs/entity/Like.ts
  srcs/entity/Notice.ts
  srcs/entity/Policy.ts
  srcs/entity/Post.ts
  srcs/entity/Question.ts
  srcs/entity/Token.ts
  srcs/entity/User.ts
  srcs/entity/common/Enums.ts
Labels: environment

#11 env: Like모델 수정
  srcs/entity/Like.ts
  srcs/entity/User.ts
Labels: environment

#16 Feature/#13
  @types/types.d.ts
  ormconfig.js
  package.json
  srcs/config/connectDB.ts
  srcs/controllers/controller.getAccessToken.ts
  srcs/controllers/controller.signinKakao.ts
  srcs/controllers/index.ts
  srcs/entity/Policy.ts
  srcs/entity/Question.ts
  srcs/entity/Token.ts
  srcs/entity/User.ts
  srcs/entity/index.ts
  srcs/lib/auth.lib.ts
  srcs/lib/index.ts
  srcs/middleware/index.ts
  srcs/middleware/middleware.isAuth.ts
  srcs/middleware/middleware.validator.ts
  srcs/repository/index.ts
  srcs/repository/repository.token.ts
  srcs/repository/repository.user.ts
  srcs/routes/index.ts
Labels: feature

#18 env: 정책 데이터 인풋 코드 작성
  docker-compose.yml
  package.json
  proxy/Dockerfile
  proxy/nginx.conf
  srcs/entity/Like.ts
  srcs/entity/Policy.ts
  srcs/inputData.ts
Labels: environment

#24 Feature/#21
  srcs/controllers/controller.getPolicyDetail.ts
  srcs/controllers/controller.getPolicyList.ts
  srcs/controllers/controller.likePolicy.ts
  srcs/controllers/index.ts
  srcs/entity/Like.ts
  srcs/repository/index.ts
  srcs/repository/repository.policy.ts
  srcs/routes/index.ts
  srcs/swagger/controller/getPolicy.ts
  srcs/swagger/controller/likePolicy.ts
  srcs/swagger/schema/like.ts
  srcs/swagger/schema/policy.ts
Labels: feature

#23 Environment/#22
  package.json
  srcs/inputData.ts
Labels: environment

#27 feat: updateOneUserById 함수 구현
  .DS_Store
  srcs/.DS_Store
  srcs/controllers/controller.patchUserNickname.ts
  srcs/controllers/index.ts
  srcs/repository/index.ts
  srcs/repository/repository.user.ts
  srcs/routes/index.ts
Labels: feature

#31 fix: getToken 에러처리 수정
  srcs/controllers/controller.getAccessToken.ts
  srcs/controllers/controller.signoutKakao.ts
  srcs/controllers/controller.signoutNaver.ts
Labels: hotfix

#32 Feature/#21
  srcs/controllers/controller.getFilteredPolicyList.ts
  srcs/controllers/controller.getPolicyDetail.ts
  srcs/controllers/controller.getPolicyList.ts
  srcs/controllers/controller.likePolicy.ts
  srcs/controllers/controller.patchUserNickname.ts
  srcs/controllers/index.ts
  srcs/repository/repository.policy.ts
  srcs/routes/index.ts
  srcs/swagger/controller/getPolicy.ts
  srcs/swagger/controller/likePolicy.ts
  srcs/swagger/schema/policy.ts
  srcs/swagger/schema/user.ts
Labels: feature

#39 Feature/#36
  srcs/controllers/controller.getCommunityList.ts
  srcs/controllers/index.ts
  srcs/repository/index.ts
  srcs/repository/repository.posts.ts
  srcs/routes/index.ts
  srcs/swagger/controller/getPosts.ts
  srcs/swagger/schema/post.ts
Labels: feature

#38 하나의 user 조회 후 반환하는 api 구현
  srcs/controllers/controller.getOneUser.ts
  srcs/controllers/controller.patchUserFilterInfo.ts
  srcs/controllers/index.ts
  srcs/lib/date.lib.ts
  srcs/routes/index.ts
Labels: feature

#41 Feature/#40
  srcs/controllers/controller.getOneUserPosts.ts
  srcs/controllers/index.ts
  srcs/repository/index.ts
  srcs/repository/repository.posts.ts
  srcs/routes/index.ts
Labels: feature

#48 feat: 한 user가 작성한 댓글에 대한 정보 조회 api 구현
  srcs/controllers/controller.getOneUserComments.ts
  srcs/controllers/index.ts
  srcs/repository/index.ts
  srcs/repository/repository.comment.ts
  srcs/routes/index.ts
Labels: feature

#51 feat: 마이페이지 - 찜목록
  srcs/controllers/controller.getOneUserLikePolicy.ts
  srcs/controllers/index.ts
  srcs/repository/index.ts
  srcs/repository/repository.policy.ts
  srcs/routes/index.ts
Labels: feature

#50 feat: 커뮤니티 글 상세 페이지 api response 수정
  srcs/controllers/controller.getPostDetail.ts
  srcs/repository/index.ts
  srcs/repository/repository.comment.ts
  srcs/repository/repository.posts.ts
  srcs/routes/index.ts
Labels: feature

#52 feat: 커뮤니티 포스트 작성 api
  @types/types.d.ts
  srcs/controllers/controller.postCommunityPost.ts
  srcs/controllers/index.ts
  srcs/repository/index.ts
  srcs/repository/repository.posts.ts
  srcs/routes/index.ts
  srcs/swagger/controller/postCommunityPost.ts
  srcs/swagger/schema/post.ts
Labels: feature

#54 Docs/#53: swagger api 문서 작성
  srcs/controllers/controller.getOneUserComments.ts
  srcs/controllers/controller.getOneUserPosts.ts
  srcs/repository/repository.comment.ts
  srcs/repository/repository.policy.ts
  srcs/repository/repository.posts.ts
  srcs/repository/repository.user.ts
  srcs/swagger/controller/auth.ts
  srcs/swagger/controller/getUser.ts
  srcs/swagger/schema/comment.ts
  srcs/swagger/schema/policy.ts
  srcs/swagger/schema/post.ts
  srcs/swagger/schema/user.ts
Labels: docs

#55 feat: 커뮤니티 검색 api
  srcs/controllers/controller.searchCommunity.ts
  srcs/controllers/index.ts
  srcs/repository/index.ts
  srcs/repository/repository.posts.ts
  srcs/routes/index.ts
  srcs/swagger/controller/searchCommunity.ts
Labels: feature

#57 docs: policy 관련 api 문서 작성 완료
  srcs/controllers/controller.getCommunityList.ts
  srcs/controllers/controller.getPostDetail.ts
  srcs/routes/index.ts
  srcs/swagger/controller/getPolicy.ts
  srcs/swagger/controller/getPosts.ts
  srcs/swagger/controller/getUser.ts
  srcs/swagger/controller/likePolicy.ts
  srcs/swagger/controller/postComment.ts
  srcs/swagger/controller/postCommunityPost.ts
  srcs/swagger/controller/searchCommunity.ts
  srcs/swagger/schema/comment.ts
  srcs/swagger/schema/error.ts
  srcs/swagger/schema/post.ts
Labels: docs

#67 Feature: 공지사항 조회 api
  srcs/controllers/controller.getNotice.ts
  srcs/controllers/index.ts
  srcs/entity/Notice.ts
  srcs/repository/index.ts
  srcs/repository/repository.notice.ts
  srcs/routes/index.ts
Labels: feature

#70 Feature/#36
  srcs/controllers/controller.deleteComment.ts
  srcs/controllers/controller.deletePost.ts
  srcs/controllers/controller.patchComment.ts
  srcs/controllers/controller.patchCommunityPost.ts
  srcs/controllers/index.ts
  srcs/repository/index.ts
  srcs/repository/repository.comment.ts
  srcs/repository/repository.posts.ts
  srcs/routes/index.ts
  srcs/swagger/controller/getPosts.ts
  srcs/swagger/controller/patchComment.ts
  srcs/swagger/controller/patchCommunityPost.ts
  srcs/swagger/schema/comment.ts
Labels: feature

#75 feat: home 찜한 정책 3개 가져오는 api
  srcs/controllers/controller.getHome.ts
  srcs/controllers/controller.patchCommunityPost.ts
  srcs/controllers/index.ts
  srcs/repository/index.ts
  srcs/repository/repository.policy.ts
  srcs/routes/index.ts
  srcs/swagger/controller/getPolicy.ts
  srcs/swagger/schema/policy.ts
Labels: feature

#78 fix: get /custom/policy => put /custom/policy 로 변경
  srcs/controllers/index.ts
  srcs/routes/index.ts
  srcs/swagger/controller/getPolicy.ts
Labels: hotfix
