Repository dnd-side-project/dnd-6th-5-backend, pull requests merged in 2022-04, with the labels that each got.

#130 env: https 적용 - nginx.conf 파일 수정
  proxy/nginx.conf
Labels: environment

#131 Hotfix/#129
  srcs/controllers/controller.signinKakao.ts
  srcs/controllers/controller.signinNaver.ts
  srcs/lib/index.ts
  srcs/lib/setObj.lib.ts
Labels: hotfix

#134 Feature/#133
  .gitignore
  package.json
  srcs/app.ts
  srcs/config/index.ts
  srcs/config/logger.ts
  srcs/index.ts
  srcs/middleware/index.ts
  srcs/middleware/middleware.originLogger.ts
  srcs/routes/index.ts
Labels: feature

#137 Feature/#136
  srcs/middleware/middleware.originLogger.ts
Labels: feature

#139 test: getPolicyDetail 유닛/통합 테스트 코드 작성
  __tests__/data/error.json
  __tests__/data/policyDetail.json
  __tests__/integration/policy/getPolicyDetail.int.test.ts
  __tests__/unit/policy/getPolicyDetail.unit.test.ts
Labels: test

#142 Feature/#141
  srcs/controllers/controller.commentReport.ts
  srcs/controllers/index.ts
  srcs/entity/Comment.ts
  srcs/entity/Report.ts
  srcs/entity/common/Enums.ts
  srcs/repository/index.ts
  srcs/repository/repository.comment.ts
  srcs/repository/repository.posts.ts
  srcs/routes/index.ts
  srcs/swagger/controller/commentReport.ts
Labels: feature

#140 feat: cors origin, methods 설정
  srcs/app.ts
Labels: feature

#146 Feature/#145
  srcs/controllers/controller.blockUser.ts
  srcs/controllers/index.ts
  srcs/entity/Block.ts
  srcs/entity/User.ts
  srcs/entity/index.ts
  srcs/repository/index.ts
  srcs/repository/repository.user.ts
  srcs/routes/index.ts
  srcs/swagger/controller/blockUser.ts
Labels: feature

#148 Feature/#147
  srcs/controllers/controller.getCommunityList.ts
  srcs/controllers/controller.getPostDetail.ts
  srcs/controllers/controller.searchCommunity.ts
  srcs/repository/index.ts
  srcs/repository/repository.block.ts
  srcs/repository/repository.posts.ts
  srcs/routes/index.ts
  srcs/swagger/controller/getPosts.ts
  srcs/swagger/controller/searchCommunity.ts
Labels: feature

#153 fix: 클라이언트 요청으로 fix작업
  srcs/controllers/controller.signinKakao.ts
  srcs/controllers/controller.signinNaver.ts
  srcs/controllers/controller.signoutNaver.ts
  srcs/repository/repository.posts.ts
Labels: hotfix

#156 feat: 안드 요청 반영 - 글 상세에 작성자 pk 추가
  srcs/repository/repository.posts.ts
  srcs/swagger/schema/comment.ts
  srcs/swagger/schema/post.ts
Labels: feature
