Repository dnd-side-project/dnd-6th-5-backend, pull requests merged in 2022-03, with the labels that each got.

#81 test: patchUserNickname controller test code작성
  @types/types.d.ts
  __tests__/data/new-user.json
  __tests__/integration/user.int.test.ts
  __tests__/simple.test.ts
  __tests__/unit/user.unit.test.ts
  jest.config.js
  ormconfig.js
  package.json
  srcs/app.ts
  srcs/config/connectDB.ts
  srcs/controllers/controller.patchUserNickname.ts
  srcs/index.ts
  srcs/repository/repository.user.ts
  srcs/routes/index.ts
  tsconfig.json
Labels: test

#91 docs: swagger api 문서 수정
  srcs/swagger/controller/getUser.ts
  srcs/swagger/schema/policy.ts
Labels: docs

#98 feat: createUser 함수 수정
  .DS_Store
  srcs/.DS_Store
  srcs/repository/repository.user.ts
Labels: feature

#100 Test/#90: getOneUser unittest code , 통합테스트 code 작성
  __tests__/data/error.json
  __tests__/data/new-user.json
  __tests__/integration/user.int.test.ts
  __tests__/integration/user/getOneUser.int.test.ts
  __tests__/integration/user/patchUserNickname.int.test.ts
  __tests__/unit/user/getOneUser.unit.test.ts
  __tests__/unit/user/patchUserNickname.unit.test.ts
  srcs/controllers/controller.getOneUser.ts
  srcs/repository/repository.user.ts
Labels: test

#103 env#102 : test DB 연결 설정
  ormconfig.js
  package.json
  srcs/config/connectDB.ts
Labels: environment

#105 feat: getNotice 컨트롤러에 에러핸들링 미들웨어 적용
  __tests__/data/result.json
  __tests__/integration/notice/getNotice.int.test.ts
  __tests__/unit/notice/getNotice.unit.test.ts
  __tests__/unit/user/getOneUser.unit.test.ts
  __tests__/unit/user/patchUserNickname.unit.test.ts
  ormconfig.js
  package.json
  srcs/config/connectDB.ts
  srcs/controllers/controller.getNotice.ts
  srcs/repository/repository.notice.ts
Labels: test

#108 Feature/#107
  srcs/controllers/controller.checkNicknameDuplicate.ts
  srcs/swagger/controller/getUser.ts
Labels: feature

#114 Feature/#112
  srcs/config/connectDB.ts
  srcs/controllers/controller.postReport.ts
  srcs/controllers/index.ts
  srcs/entity/Post.ts
  srcs/entity/Report.ts
  srcs/entity/User.ts
  srcs/entity/common/Enums.ts
  srcs/entity/index.ts
  srcs/repository/index.ts
  srcs/repository/repository.posts.ts
  srcs/routes/index.ts
  srcs/swagger/controller/postReport.ts
Labels: feature

#116 feat: 게시글/댓글 수정됨 표시 추가
  __tests__/data/category.json
  __tests__/data/policy.json
  srcs/repository/repository.posts.ts
  srcs/swagger/schema/comment.ts
  srcs/swagger/schema/post.ts
Labels: feature

#111 feat: 데이터 수집, DB최신화 자동화 작업
  __tests__/data/result.json
  ormconfig.js
  package.json
  srcs/entity/Policy.ts
  srcs/entity/common/Enums.ts
  srcs/inputData.ts
  updateData/updateData.ts
  updateData/updatePolicyActived.ts
Labels: feature

#117 feat : 수집한 data가 '' 빈값일 경우 '-'로 치환처리
  updateData/updateData.ts
Labels: feature

#119 env: 통합 테스트시 test DB에 연결하도록 npm test script 수정
  package.json
  srcs/routes/index.ts
Labels: environment

#122 test: test data 변경
  __tests__/data/posts.json
  __tests__/unit/user/patchUserNickname.unit.test.ts
Labels: test
